-- 🌿 Zentra Flora - Supabase Database Schema 🌿
-- Paste and execute these statements inside your Supabase SQL Editor to establish your database tables.

-- =========================================================================
-- 1. USERS TABLE
-- Stores credential-based user profiles, names, and Telegram subscriptions.
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT null,
    username TEXT UNIQUE NOT null,
    password TEXT NOT null,
    email TEXT UNIQUE NOT null,
    first_name TEXT,
    second_name TEXT,
    telegram_subscribed BOOLEAN DEFAULT false
);

-- Enable Row Level Security (RLS) on users table
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Allow unrestricted anonymous select/insert for simulation and handshake testing
CREATE POLICY "Allow public access to users" 
ON public.users 
FOR ALL 
TO anon 
USING (true) 
WITH CHECK (true);


-- =========================================================================
-- 2. SENSOR READINGS TABLE
-- Stores chronological telemetry streams dispatched by physical or simulated IoT hardware.
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.sensor_readings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT null,
    temperature FLOAT8,
    humidity FLOAT8,
    light FLOAT8,
    soil_moisture FLOAT8
);

-- Enable Row Level Security (RLS) on sensor_readings table
ALTER TABLE public.sensor_readings ENABLE ROW LEVEL SECURITY;

-- Allow unrestricted anonymous select/insert for simulation and telemetry charts
CREATE POLICY "Allow public access to sensor_readings" 
ON public.sensor_readings 
FOR ALL 
TO anon 
USING (true) 
WITH CHECK (true);
